name: Workflow with Custom Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Custom Action
        uses: extendedkalman/test-repo@v4
        with:
          message: "Hello from my custom action!"

