name: Workflow with Custom Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checking out step
        run: echo "checking out"
        shell: bash
        
      - name: Use Custom Action
        uses: extendedkalman/test-repo/.github/actions/test@main
        with:
          message: "Hello from my custom action!"

